export enum StrategyName {
  AAVE = 'Aave',
  SEAMLESS = 'Seamless',
  ZEROLEND = 'Zerolend',
  PENDLE = 'Pendle',
  AAVE_SEAMLESS = 'Aave-Seamless',
  SEAMLESS_AAVE = 'Seamless-Aave',
  AAVE_ZEROLEND = 'Aave-Zerolend',
  ZEROLEND_AAVE = 'Zerolend-Aave',
  SEAMLESS_ZEROLEND = 'Seamless-Zerolend',
  ZEROLEND_SEAMLESS = 'Zerolend-Seamless',
  AAVE_LOOPING = 'Aave-Looping',
  SEAMLESS_LOOPING = 'Seamless-Looping', //looping is currently only present in aave and borrow/withdraw can happen from aave/seamless/zerolend
  ZEROLEND_LOOPING = 'Zerolend-Looping',
  AAVE_LOOPING_AAVE = 'Aave-Looping-Aave',
  AAVE_LOOPING_SEAMLESS = 'Aave-Looping-Seamless',
  AAVE_LOOPING_ZEROLEND = 'Aave-Looping-Zerolend',
  HOP_BEEFY = 'Hop Beefy',
  AAVE_HOP_BEEFY = 'Aave-Hop Beefy',
  YEARN_V3 = 'yearn-v3',
}

export enum Action {
  APPROVE = 'Approve',
  SQUID = 'Squid',
  SUPPLY = 'Supply',
  WITHDRAW = 'Withdraw',
  BORROW = 'Borrow',
  REPAY = 'Repay',
  WITHDRAW_SUPPLY = 'Withdraw-Supply',
  BORROW_SUPPLY = 'Borrow-Supply',
  WITHDRAW_DEPOSIT = 'Withdraw-Deposit',
  BORROW_DEPOSIT = 'Borrow-Deposit',
  E_MODE = 'Set-Aave-EMode',
  APPROVE_DELEGATION = 'Approve-Delegation',
  LOOP_STRATEGY = 'Loop-Strategy',
  WITHDRAW_LOOP = 'Withdraw-Loop',
  BORROW_LOOP = 'Borrow-Loop',
  ADD_LIQUIDITY = 'Add-Liquidity',
  DEPOSIT = 'Deposit',
  PORTALS = 'Portals',
}
